### ISSUE TITLE
mqtt connection : log error

### ISSUE THREAD

**Issue by gregsyoung** [sbender9/signalk-venus-plugin#116]
when using mqtt connectivity option to venus, (cerbo) 
a recurring (every second) error is logged in server log.

![16E7A2B3-8F8F-4CA5-9BB1-5DA0F796883D](https://user-images.githubusercontent.com/18189062/191390304-4836c250-94ff-4d2f-9e5a-2baaa1dbd458.jpeg)

**Comment by sbender9** [comment]
This is coming from signalk-mqtt-gw.

**Comment by gregsyoung** [comment]
noted,  so its an error in the way that the mqtt messages are formulated by Venus OS? 
if so i guess i raise it in victron community forum?

**Comment by sbender9** [comment]
No. This is the code in the SK-mqtt-gw that is generating mqtt messages. 

Seems like something is off with a  an SK delta. I guess this could be a bad delta generated by the Venus  plugin.

**Comment by sbender9** [comment]
Are you actually using th SK-mqtt-gw plugin?

**Comment by gregsyoung** [comment]
yes, use it for other than venus also. 
its only getting error from the venus (it goes away if i disable mqtt in venus) 

Q: i can connect tomvenus via alternate method? but thought this was the easier?

**Comment by gregsyoung** [comment]
ah just checked plugin description…
im using signalk on separate rpi … 
so i can “only” use mqtt b or c methods

**Comment by sbender9** [comment]
It looks like something is generating a delta with a null or empty path. Sounds like it must be the Venus plugin if it goes away when you turn it off. 

I think it's just a coincidence that "mqtt" is involved here. 

I'll see if I can reproduce this tomorrow...

**Comment by gregsyoung** [comment]
i disabled venus plugin and restarted signalk server,
however same error (from mqtt plugin) is occuring every second in server log. 

so it wouldnt appear to be caused by venus plugin ….?

on cerbo (venus) i have the 
mqtt on lan (for both plain text and ssh) enbled.

.. so it would appear its a problem with the mqtt messages published by cerbo/venus ? 
that is read by mqtt plugin as generates an error?

**Comment by sbender9** [comment]
No. It does not sound like this has anything do to with the Cerbo.  That plugin does not read anything  from mqtt. This is happening when the gw plugin is sending out mqtt messages. 

I think something on your system is generating delta values with a null or missing path.

**Comment by sbender9** [comment]
Oh. It looks like it is coming from

/home/pi/.signalk/node_modules/signalk-speed-wind-averaging/dist/index.js:252:13)

**Comment by gregsyoung** [comment]
indeed you are correct , , disabled that plugin, and error went away,
my apologies for sending you down the wrong path. 

as always very much appreciate your assistance
