### ISSUE TITLE
Venus plugin stopping on CerboGX V3.30 and SK 2.5

### ISSUE THREAD

**Issue by x7y8z9** [sbender9/signalk-venus-plugin#135]
The pre-installed Victron venus plugin stops delivering GX data within SignalK after a undefined period of time (after 2min or up to 4h). Other plugins are working flawless. I did not change the venus plugin settings.
Data sets are either internal data created by the CerboGX like
electrical.venus.totalPanelPower (venus.com.victronenergy.system)
electrical.venus.totalPanelCurrent (venus.com.victronenergy.system)
or delivered data from ET112
electrical.grid.31.power (venus.com.victronenergy.grid.cgwacs_ttyUSB1_mb1)

Disabling and enabling the plugin brings the plugin back to life for a undefined period.

Error in ServerLog: 
Mar 25 16:53:57 TypeError: Cannot set properties of undefined (setting 'deviceInstance') at Object.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/signalk-venus-plugin/dbus-listener.js:82:44) at EventEmitter.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/dbus-native/lib/bus.js:110:19) at EventEmitter.emit (node:events:529:35) at /usr/lib/node_modules/signalk-server/node_modules/dbus-native/index.js:106:14 at Socket.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/dbus-native/lib/message.js:55:9) at Socket.emit (node:events:517:28) at emitReadable_ (node:internal/streams/readable:601:12) at process.processTicksAndRejections (node:internal/process/task_queues:81:21) 

Any idea what to do, any suggetsion for missing or wrong config?

**Comment by sbender9** [comment]
can you turn on debug for the venus plugin, then look for messages 

like

'com.victronenergy.settings is :1.53'
'warning: error getting device instance for com.victronenergy.settings' 

those messages would be right before the error above

**Comment by sbender9** [comment]
Fixed in v1.34.1

**Comment by x7y8z9** [comment]
Thx for working on my request!

It’s not offered for update, un-install & re-install isn’t possible:

***@***.***

Von: Scott Bender ***@***.***>
Gesendet: Samstag, 30. März 2024 22:24
An: sbender9/signalk-venus-plugin ***@***.***>
Cc: Joerg R. Plaschka ***@***.***>; Author ***@***.***>
Betreff: Re: [sbender9/signalk-venus-plugin] Venus plugin stopping on CerboGX V3.30 and SK 2.5 (Issue #135)


Fixed in v1.34.1

**Comment by sbender9** [comment]
It is possible to update it manually. It will be in the next Venus OS beta release.

**Comment by x7y8z9** [comment]
How do I perform a manual update?

Lesson learned: we don’t use beta releases any more on a ocean going vessel ;-)


Von: Scott Bender ***@***.***>
Gesendet: Sonntag, 31. März 2024 18:19
An: sbender9/signalk-venus-plugin ***@***.***>
Cc: Joerg R. Plaschka ***@***.***>; Author ***@***.***>
Betreff: Re: [sbender9/signalk-venus-plugin] Venus plugin stopping on CerboGX V3.30 and SK 2.5 (Issue #135)


It is possible to update it manually. It will be in the next Venus OS beta release.

**Comment by sbender9** [comment]
Of course, this is not without risk. You need ssh/root access to the device:

https://www.victronenergy.com/live/ccgx:root_access

Covered above is info about making the root partition writable, (you must run /opt/victronenergy/swupdate-scripts/resize2fs.sh)

Once that is all done. To update the plugin:

```
cd /usr/lib/node_modules/signalk-server
npm install signalk-venus-plugin@1.34.1
```

Then restart Signal K (or the device)

**Comment by x7y8z9** [comment]
Venus plugin working:

Apr 01 20:51:35 2024-04-01T20:51:35.236Z signalk-venus-plugin com.victronenergy.vecan.can0 is sender :1.9033
Apr 01 20:51:35 2024-04-01T20:51:35.260Z signalk-venus-plugin name owner change: {"serial":26295,"path":"/org/freedesktop/DBus","interface":"org.freedesktop.DBus","member":"NameOwnerChanged","sender":"org.freedesktop.DBus","signature":"sss","type":4,"flags":1,"body":["com.victronenergy.vecan.can0","",":1.9033"]}
Apr 01 20:51:35 2024-04-01T20:51:35.265Z signalk-venus-plugin com.victronenergy.vecan.can0 is sender :1.9033
Apr 01 20:51:35 2024-04-01T20:51:35.396Z signalk-venus-plugin warning: error getting device instance for com.victronenergy.vecan.can0
Apr 01 20:51:35 2024-04-01T20:51:35.403Z signalk-venus-plugin warning: error getting device instance for com.victronenergy.vecan.can0
Apr 01 20:51:35 2024-04-01T20:51:35.430Z signalk-venus-plugin name owner change: {"serial":26296,"path":"/org/freedesktop/DBus","interface":"org.freedesktop.DBus","member":"NameOwnerChanged","sender":"org.freedesktop.DBus","signature":"sss","type":4,"flags":1,"body":[":1.9034","",":1.9034"]}
Apr 01 20:51:35 2024-04-01T20:51:35.433Z signalk-venus-plugin name owner change: {"serial":26296,"path":"/org/freedesktop/DBus","interface":"org.freedesktop.DBus","member":"NameOwnerChanged","sender":"org.freedesktop.DBus","signature":"sss","type":4,"flags":1,"body":[":1.9034","",":1.9034"]}

...

Apr 01 21:00:54 2024-04-01T21:00:54.804Z signalk-venus-plugin name owner change: {"serial":27642,"path":"/org/freedesktop/DBus","interface":"org.freedesktop.DBus","member":"NameOwnerChanged","sender":"org.freedesktop.DBus","signature":"sss","type":4,"flags":1,"body":[":1.9484",":1.9484",""]}
Apr 01 21:00:54 2024-04-01T21:00:54.810Z signalk-venus-plugin warning: error during GetValue on / for com.victronenergy.vecan.can0 Message recipient disconnected from message bus without replying
Apr 01 21:00:54 2024-04-01T21:00:54.813Z signalk-venus-plugin name owner change: {"serial":27643,"path":"/org/freedesktop/DBus","interface":"org.freedesktop.DBus","member":"NameOwnerChanged","sender":"org.freedesktop.DBus","signature":"sss","type":4,"flags":1,"body":[":1.9485",":1.9485",""]}



Restart of CerboGX = Venus plugin not working:

Apr 01 21:18:36 [signalk-to-nmea0183] GGA: no position, not converting
Apr 01 21:18:42 2024-04-01T21:18:42.988Z signalk-venus-plugin Dbus connection attempt 1
Apr 01 21:18:43 2024-04-01T21:18:43.004Z signalk-venus-plugin Connecting null
Apr 01 21:18:43 signalk-server running at 0.0.0.0:3000
Apr 01 21:18:48 2024-04-01T21:18:48.381Z signalk-venus-plugin name owner change: {"serial":19,"path":"/org/freedesktop/DBus","interface":"org.freedesktop.DBus","member":"NameOwnerChanged","sender":"org.freedesktop.DBus","signature":"sss","type":4,"flags":1,"body":["com.victronenergy.vecan.can0",":1.243",""]}
Apr 01 21:18:48 2024-04-01T21:18:48.389Z signalk-venus-plugin name owner change: {"serial":20,"path":"/org/freedesktop/DBus","interface":"org.freedesktop.DBus","member":"NameOwnerChanged","sender":"org.freedesktop.DBus","signature":"sss","type":4,"flags":1,"body":[":1.243",":1.243",""]}
Apr 01 21:18:48 2024-04-01T21:18:48.394Z signalk-venus-plugin name owner change: {"serial":21,"path":"/org/freedesktop/DBus","interface":"org.freedesktop.DBus","member":"NameOwnerChanged","sender":"org.freedesktop.DBus","signature":"sss","type":4,"flags":1,"body":[":1.244",":1.244",""]}
Apr 01 21:18:48 2024-04-01T21:18:48.399Z signalk-venus-plugin name owner change: {"serial":22,"path":"/org/freedesktop/DBus","interface":"org.freedesktop.DBus","member":"NameOwnerChanged","sender":"org.freedesktop.DBus","signature":"sss","type":4,"flags":1,"body":[":1.246","",":1.246"]}
Apr 01 21:18:48 2024-04-01T21:18:48.403Z signalk-venus-plugin name owner change: {"serial":23,"path":"/org/freedesktop/DBus","interface":"org.freedesktop.DBus","member":"NameOwnerChanged","sender":"org.freedesktop.DBus","signature":"sss","type":4,"flags":1,"body":["com.victronenergy.vecan.can0","",":1.246"]}
Apr 01 21:18:48 2024-04-01T21:18:48.444Z signalk-venus-plugin com.victronenergy.vecan.can0 is sender :1.246
Apr 01 21:18:48 2024-04-01T21:18:48.460Z signalk-venus-plugin name owner change: {"serial":24,"path":"/org/freedesktop/DBus","interface":"org.freedesktop.DBus","member":"NameOwnerChanged","sender":"org.freedesktop.DBus","signature":"sss","type":4,"flags":1,"body":[":1.247","",":1.247"]}
Apr 01 21:18:50 2024-04-01T21:18:50.784Z signalk-venus-plugin com.victronenergy.battery.ttyUSB4 is sender :1.104
Apr 01 21:18:50 2024-04-01T21:18:50.796Z signalk-venus-plugin com.victronenergy.settings is sender :1.72
Apr 01 21:18:50 2024-04-01T21:18:50.813Z signalk-venus-plugin com.victronenergy.vecan.can0 is sender :1.246
Apr 01 21:18:50 2024-04-01T21:18:50.829Z signalk-venus-plugin com.victronenergy.system is sender :1.56
Apr 01 21:18:50 2024-04-01T21:18:50.845Z signalk-venus-plugin com.victronenergy.fronius is sender :1.90
Apr 01 21:18:50 2024-04-01T21:18:50.873Z signalk-venus-plugin com.victronenergy.platform is sender :1.96
Apr 01 21:18:50 2024-04-01T21:18:50.909Z signalk-venus-plugin com.victronenergy.solarcharger.ttyUSB2 is sender :1.93
Apr 01 21:18:50 2024-04-01T21:18:50.967Z signalk-venus-plugin com.victronenergy.solarcharger.ttyUSB3 is sender :1.99
Apr 01 21:18:51 2024-04-01T21:18:51.001Z signalk-venus-plugin com.victronenergy.solarcharger.ttyUSB5 is sender :1.110
Apr 01 21:18:51 2024-04-01T21:18:51.024Z signalk-venus-plugin com.victronenergy.modbusclient.tcp is sender :1.67
Apr 01 21:18:51 2024-04-01T21:18:51.043Z signalk-venus-plugin com.victronenergy.dcsystem.aggregator is sender :1.32
Apr 01 21:18:51 2024-04-01T21:18:51.075Z signalk-venus-plugin com.victronenergy.grid.cgwacs_ttyUSB1_mb1 is sender :1.115
Apr 01 21:18:51 2024-04-01T21:18:51.095Z signalk-venus-plugin com.victronenergy.packageManager is sender :1.50
Apr 01 21:18:51 2024-04-01T21:18:51.114Z signalk-venus-plugin com.victronenergy.battery.aggregator is sender :1.47
Apr 01 21:18:51 2024-04-01T21:18:51.137Z signalk-venus-plugin com.victronenergy.battery.ttyS5 is sender :1.73
Apr 01 21:18:51 2024-04-01T21:18:51.147Z signalk-venus-plugin com.victronenergy.ble is sender :1.107
Apr 01 21:18:51 2024-04-01T21:18:51.155Z signalk-venus-plugin com.victronenergy.battery.ttyS6 is sender :1.75
Apr 01 21:18:51 2024-04-01T21:18:51.171Z signalk-venus-plugin com.victronenergy.logger is sender :1.103
Apr 01 21:18:51 2024-04-01T21:18:51.181Z signalk-venus-plugin com.victronenergy.adc is sender :1.89
Apr 01 21:18:51 2024-04-01T21:18:51.190Z signalk-venus-plugin com.victronenergy.tank.adc_builtin0_1 is sender :1.95
Apr 01 21:18:51 2024-04-01T21:18:51.199Z signalk-venus-plugin com.victronenergy.shutdown is sender :1.38
Apr 01 21:18:51 2024-04-01T21:18:51.210Z signalk-venus-plugin com.victronenergy.tank.adc_builtin0_2 is sender :1.94
Apr 01 21:18:51 2024-04-01T21:18:51.217Z signalk-venus-plugin com.victronenergy.battery.ttyUSB0 is sender :1.79
Apr 01 21:18:51 2024-04-01T21:18:51.235Z signalk-venus-plugin warning: error getting device instance for com.victronenergy.vecan.can0
Apr 01 21:18:51 2024-04-01T21:18:51.324Z signalk-venus-plugin name owner change: {"serial":25,"path":"/org/freedesktop/DBus","interface":"org.freedesktop.DBus","member":"NameOwnerChanged","sender":"org.freedesktop.DBus","signature":"sss","type":4,"flags":1,"body":[":1.247",":1.247",""]}
Apr 01 21:18:51 2024-04-01T21:18:51.327Z signalk-venus-plugin name owner change: {"serial":26,"path":"/org/freedesktop/DBus","interface":"org.freedesktop.DBus","member":"NameOwnerChanged","sender":"org.freedesktop.DBus","signature":"sss","type":4,"flags":1,"body":["com.victronenergy.vecan.can0",":1.246",""]}
Apr 01 21:18:51 2024-04-01T21:18:51.331Z signalk-venus-plugin name owner change: {"serial":27,"path":"/org/freedesktop/DBus","interface":"org.freedesktop.DBus","member":"NameOwnerChanged","sender":"org.freedesktop.DBus","signature":"sss","type":4,"flags":1,"body":[":1.246",":1.246",""]}
Apr 01 21:18:51 2024-04-01T21:18:51.336Z signalk-venus-plugin name owner change: {"serial":28,"path":"/org/freedesktop/DBus","interface":"org.freedesktop.DBus","member":"NameOwnerChanged","sender":"org.freedesktop.DBus","signature":"sss","type":4,"flags":1,"body":[":1.248","",":1.248"]}
Apr 01 21:18:51 2024-04-01T21:18:51.338Z signalk-venus-plugin name owner change: {"serial":29,"path":"/org/freedesktop/DBus","interface":"org.freedesktop.DBus","member":"NameOwnerChanged","sender":"org.freedesktop.DBus","signature":"sss","type":4,"flags":1,"body":["com.victronenergy.vecan.can0","",":1.248"]}
Apr 01 21:18:51 2024-04-01T21:18:51.340Z signalk-venus-plugin com.victronenergy.vecan.can0 is sender :1.248
Apr 01 21:18:51 2024-04-01T21:18:51.350Z signalk-venus-plugin name owner change: {"serial":30,"path":"/org/freedesktop/DBus","interface":"org.freedesktop.DBus","member":"NameOwnerChanged","sender":"org.freedesktop.DBus","signature":"sss","type":4,"flags":1,"body":[":1.249","",":1.249"]}
Apr 01 21:18:52 2024-04-01T21:18:52.055Z signalk-venus-plugin warning: error getting device instance for com.victronenergy.vecan.can0
Apr 01 21:18:52 TypeError: Cannot set properties of undefined (setting 'deviceInstance') at Object.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/signalk-venus-plugin/dbus-listener.js:82:44) at EventEmitter.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/dbus-native/lib/bus.js:110:19) at EventEmitter.emit (node:events:529:35) at /usr/lib/node_modules/signalk-server/node_modules/dbus-native/index.js:106:14 at Socket.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/dbus-native/lib/message.js:55:9) at Socket.emit (node:events:517:28) at emitReadable_ (node:internal/streams/readable:601:12) at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
Apr 01 21:18:57 invalid input to toNmeaDegreesLatitude: -180439788082429950
Apr 01 21:18:57 invalid input to toNmeaDegreesLatitude: -180439788082429950
Apr 01 21:18:59 GET /admin/ 200 2176.728 ms - 562
Apr 01 21:19:02 GET /admin/ 200 2405.570 ms - 562
Apr 01 21:19:02 GET /skServer/debugKeys 200 63.732 ms - -
Apr 01 21:19:04 GET /admin/main.js 304 304.512 ms - -
Apr 01 21:19:04 GET ***@***.***/vesselpositions/remoteEntry.js 304 967.480 ms - -
Apr 01 21:19:04 GET /skServer/debugKeys 200 13.156 ms - -
Apr 01 21:19:05 GET /admin/79.js 304 47.178 ms - -
Apr 01 21:19:05 GET /admin/784.js 304 41.395 ms - -
Apr 01 21:19:05 GET /admin/316.js 304 31.382 ms - -
Apr 01 21:19:05 GET /admin/270.js 304 12.868 ms - -
Apr 01 21:19:07 GET /skServer/debugKeys 304 10.859 ms - -
Apr 01 21:19:07 GET /skServer/loginStatus 200 14.936 ms - 204
Apr 01 21:19:08 GET /skServer/plugins 200 170.492 ms - -
Apr 01 21:19:08 GET /skServer/addons 304 111.291 ms - -
Apr 01 21:19:09 GET /skServer/webapps 304 90.479 ms - -
Apr 01 21:19:10 GET /skServer/security/access/requests 304 16.107 ms - -
Apr 01 21:19:10 GET /signalk 304 104.682 ms - -
Apr 01 21:19:11 GET /admin/fonts/signal-k-logo-image-text.d132ec2c4f0269c103c868aaa6868f01.svg 200 1797.124 ms - -
Apr 01 21:19:23 GET /skServer/appstore/available 304 15294.530 ms - -
Apr 01 21:19:36 GET /skServer/plugins 200 84.180 ms - -
Apr 01 21:19:38 invalid input to toNmeaDegreesLatitude: -180439788082429950
Apr 01 21:19:38 invalid input to toNmeaDegreesLatitude: -180439788082429950
Apr 01 21:19:38 invalid input to toNmeaDegreesLatitude: -180439788082429950
Apr 01 21:19:42 GET /skServer/availablePaths 200 11.929 ms - -
Apr 01 21:19:42 GET /skServer/providers 304 39.778 ms - -
Apr 01 21:19:42 PUT /skServer/runDiscovery 200 147.216 ms - 17
Apr 01 21:19:42 GET /signalk/v1/api/vessels/self/ 200 64.966 ms - -
Apr 01 21:19:44 GET /skServer/debugKeys 304 16.859 ms - -
Apr 01 21:20:38 invalid input to toNmeaDegreesLatitude: -180439788082429950
Apr 01 21:20:38 invalid input to toNmeaDegreesLatitude: -180439788082429950
Apr 01 21:20:38 invalid input to toNmeaDegreesLatitude: -180439788082429950
Apr 01 21:21:38 invalid input to toNmeaDegreesLatitude: -180439788082429950
Apr 01 21:21:38 invalid input to toNmeaDegreesLatitude: -180439788082429950
Apr 01 21:22:38 invalid input to toNmeaDegreesLatitude: -180439788082429950
Apr 01 21:22:38 invalid input to toNmeaDegreesLatitude: -180439788082429950
Apr 01 21:22:38 invalid input to toNmeaDegreesLatitude: -180439788082429950
Apr 01 21:23:24 GET /admin/ 200 294.462 ms - 562
Apr 01 21:23:25 GET ***@***.***/vesselpositions/remoteEntry.js 304 129.104 ms - -
Apr 01 21:23:25 GET /admin/main.js 304 32.660 ms - -
Apr 01 21:23:25 GET /admin/79.js 304 76.094 ms - -
Apr 01 21:23:25 GET /admin/784.js 304 49.743 ms - -
Apr 01 21:23:25 GET /admin/316.js 304 15.494 ms - -
Apr 01 21:23:25 GET /admin/270.js 304 12.423 ms - -
Apr 01 21:23:26 GET /skServer/debugKeys 304 8.525 ms - -
Apr 01 21:23:26 GET /skServer/plugins 304 63.042 ms - -
Apr 01 21:23:26 GET /skServer/webapps 304 25.440 ms - -
Apr 01 21:23:26 GET /skServer/addons 304 13.185 ms - -
Apr 01 21:23:26 GET /skServer/loginStatus 200 10.679 ms - 204
Apr 01 21:23:26 GET /signalk 304 140.899 ms - -
Apr 01 21:23:26 GET /skServer/security/access/requests 304 12.310 ms - -
Apr 01 21:23:26 GET /admin/fonts/signal-k-logo-image-text.d132ec2c4f0269c103c868aaa6868f01.svg 200 449.803 ms - -
Apr 01 21:23:31 GET /skServer/appstore/available 304 4693.963 ms - -

**Comment by x7y8z9** [comment]
One more:


Apr 01 22:01:06 TypeError: Cannot set properties of undefined (setting 'deviceInstance') at Object.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/signalk-venus-plugin/dbus-listener.js:82:44) at EventEmitter.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/dbus-native/lib/bus.js:110:19) at EventEmitter.emit (node:events:529:35) at /usr/lib/node_modules/signalk-server/node_modules/dbus-native/index.js:106:14 at Socket.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/dbus-native/lib/message.js:55:9) at Socket.emit (node:events:517:28) at emitReadable_ (node:internal/streams/readable:601:12) at process.processTicksAndRejections (node:internal/process/task_queues:81:21)


________________________________
Von: Scott Bender ***@***.***>
Gesendet: Samstag, 30. März 2024 20:51
An: sbender9/signalk-venus-plugin
Cc: Joerg R. Plaschka; Author
Betreff: Re: [sbender9/signalk-venus-plugin] Venus plugin stopping on CerboGX V3.30 and SK 2.5 (Issue #135)


can you turn on debug for the venus plugin, then look for messages

like

'com.victronenergy.settings is :1.53'
'warning: error getting device instance for com.victronenergy.settings'

those messages would be right before the error above

**Comment by sbender9** [comment]
You installed the new version of the plugin?

**Comment by x7y8z9** [comment]
No still 1.34.0

Von: Scott Bender ***@***.***>
Gesendet: Dienstag, 2. April 2024 00:20
An: sbender9/signalk-venus-plugin ***@***.***>
Cc: Joerg R. Plaschka ***@***.***>; Author ***@***.***>
Betreff: Re: [sbender9/signalk-venus-plugin] Venus plugin stopping on CerboGX V3.30 and SK 2.5 (Issue #135)


You installed the new version of the plugin?

**Comment by x7y8z9** [comment]
New experience on 1.34.0:

After the plugin went offline (= not shown on SK Dashboard)

as soon as I turn on “Enable debug log” the plugin starts working and is shown on the Dashboard


Von: Scott Bender ***@***.***>
Gesendet: Dienstag, 2. April 2024 00:20
An: sbender9/signalk-venus-plugin ***@***.***>
Cc: Joerg R. Plaschka ***@***.***>; Author ***@***.***>
Betreff: Re: [sbender9/signalk-venus-plugin] Venus plugin stopping on CerboGX V3.30 and SK 2.5 (Issue #135)


You installed the new version of the plugin?

**Comment by x7y8z9** [comment]
There is still no offer to update the venus plugin.

Why do I receive updates for other pre-installed plugins – like today morning, see below - but not to update the venus plugin?
***@***.***


Von: Scott Bender ***@***.***>
Gesendet: Dienstag, 2. April 2024 00:20
An: sbender9/signalk-venus-plugin ***@***.***>
Cc: Joerg R. Plaschka ***@***.***>; Author ***@***.***>
Betreff: Re: [sbender9/signalk-venus-plugin] Venus plugin stopping on CerboGX V3.30 and SK 2.5 (Issue #135)


You installed the new version of the plugin?

**Comment by x7y8z9** [comment]
Yes, I installed the update for the CerboGX V3.31 incl. SK 2.7.1 incl. v1.34.1 of venus plugin, kept it 24h running and the issue is solved. Even on a restart the plugin starts working.

Thank you!

Von: Scott Bender ***@***.***>
Gesendet: Montag, 1. April 2024 23:20
An: sbender9/signalk-venus-plugin ***@***.***>
Cc: Joerg R. Plaschka ***@***.***>; Author ***@***.***>
Betreff: Re: [sbender9/signalk-venus-plugin] Venus plugin stopping on CerboGX V3.30 and SK 2.5 (Issue #135)


You installed the new version of the plugin?
