### ISSUE TITLE
Add Alternator Field Value Path data

### ISSUE THREAD

**Issue by scurvy-dog** [sbender9/signalk-venus-plugin#138]
Request to add the following data path be added to the export out of the Venus.
- Alternator field value. Should be bound 0-100% 

Append to parent path of
electrical.alternator.X.

Thank you.

**Comment by sbender9** [comment]
Released in 1.35.0

I don't have any way to test, so please let me know...

**Comment by scurvy-dog** [comment]
Will test and get back to you on results.

**Comment by scurvy-dog** [comment]
field addition validated and working
