### ISSUE TITLE
Not receiving deltas after update

### ISSUE THREAD

**Issue by Fgonzalez22** [sbender9/signalk-venus-plugin#147]
Running raspberry pi with venus os, and another raspberry with openplotter. I have been using the venus plugin for more than a year without issues but after the last update even though signalk states the Venus plugin is started, no deltas are coming in.
Connections have not changed via MQQT Plain text, but I see a password field that wasn't there before. Could that be the issue?

The server log for the venus pluggin looks like this: 

Aug 11 18:47:57 2024-08-11T21:47:57.728Z signalk-venus-plugin mqtt reconnect
Aug 11 18:47:57 2024-08-11T21:47:57.739Z signalk-venus-plugin mqtt close
Aug 11 18:47:58 2024-08-11T21:47:58.739Z signalk-venus-plugin mqtt reconnect
Aug 11 18:47:58 2024-08-11T21:47:58.754Z signalk-venus-plugin mqtt close
Aug 11 18:47:59 2024-08-11T21:47:59.753Z signalk-venus-plugin mqtt reconnect

Thanks!

**Comment by sbender9** [comment]
Yeah. I might have broken something. You can revert to the previous major release.

**Comment by Fgonzalez22** [comment]
Thanks for your feedback! I will do as suggested. How do I go back to previous major release? I don't see in the signalk AppStore the possibility of reverting to previous versions or to delete and choose which version to reinstall. 
Can you provide me with some guidelines on how to do that. 

Thanks for your help!

**Comment by Fgonzalez22** [comment]
Scott, any help or guideline in how to revert or install previous versions from SK AppStore? Would save me !

**Comment by sbender9** [comment]
Sorry, and I totally forgot about this!

```
cd ~/.signalk
npm install --no-save signalk-venus-plugin@1.37.0
```

**Comment by sbender9** [comment]
What version of Venu OS are you running?

**Comment by Fgonzalez22** [comment]
> npm install --no-save signalk-venus-plugin@1.37.0

Thanks Scott, its working fine with 1.37.0 !

**Comment by Fgonzalez22** [comment]
> Have you tried with 1.38.1 ?

That's the last one available for me, it stopped working when i installed it

**Comment by Fgonzalez22** [comment]
> What version of Venu OS are you running?

Running v3.30
Quite recent but not the last one, since I have made many adaptations, to include analog and digital inputs, relays, etc. that have quite some work to be done once its updated.

**Comment by sbender9** [comment]
So far, I can't reproduce your issue. How do you have the plugin configured? Is is MQTT Plain Text or SSL?

**Comment by sbender9** [comment]
And you just got the close/reconnect messages? No other error message at all?

**Comment by Fgonzalez22** [comment]
> So far, I can't reproduce your issue. How do you have the plugin configured? Is is MQTT Plain Text or SSL?

Its MQTT Plain Text...  Host: venus.local

**Comment by Fgonzalez22** [comment]
> And you just got the close/reconnect messages? No other error message at all?

Yes that's all i got. No other errors. Now after re-intalling previous version it re-started directly. No need for any setup.

**Comment by Fgonzalez22** [comment]
I have not updated to the last version since that was the one that was causing the problem. I went back to signalk-venus-plugin@1.37.0.
Should I re install the latest version?

**Comment by Fgonzalez22** [comment]
I can confirm that lastest version is not working for me. Again went back v1.37.0

**Comment by sbender9** [comment]
can you please try with v1.39.0 when you have a chance?

**Comment by Fgonzalez22** [comment]
Testing v1.39.0 restarted openplotter and venus and seems ok. Cannot restart router at this time, just in case that may be the cause the link could not been established. I'll let you know how things go on. Thanks
