### ISSUE TITLE
Feature request : Add sensor battery level and device status for Ruuvitag 

### ISSUE THREAD

**Issue by torbenaa** [sbender9/signalk-venus-plugin#156]
Hi Scott,

Wouldn't it be nice if we could get batteri levels and perhaps device status from Ruuvitags ? The data is there on the Cerbo frontpage.

I'll be happy to test - I have the 410D and the 8490 connected to my Cerbo.

Thanks !

Br Torben

**Comment by sbender9** [comment]
Done an released https://github.com/sbender9/signalk-venus-plugin/releases/tag/v1.41.0

**Comment by torbenaa** [comment]
That was really quick !

I rushed to the boat to try it out - but then realised that I cannot upgrade the plugin on Venus OS large :(

I guess I have to wait for a new release  - or is there a way to work around this ?

Thanks a lot, Scott.

**Comment by torbenaa** [comment]
Well - I took the chance and replaced the updated files in /usr/lib/node_modules/signalk-server/node_modules/signalk-venus-plugin
And viola - I now have voltage, status, and statusNumber for both devices !

Can't wait to have this as part of the official Venus OS Large.
