### ISSUE TITLE
Adding Frequency - Should I submit PR?

### ISSUE THREAD

**Issue by dpreuss** [sbender9/signalk-venus-plugin#41]
I see frequency was missing, so I added it to my install. I can submit PR if you would prefer. 

    '/Ac/ActiveIn/L1/F': {
      path: m => {
        return makePath(m, `${m.instanceName}.acin.frequency`, true)
      }
    },

...
    '/Ac/Out/L1/F': {
      path: m => {
        return makePath(m, `${m.instanceName}.acout.frequency`, true)
      }
    },

**Comment by sbender9** [comment]
A PR would be great. Thanks!
