### ISSUE TITLE
numbering (USB) devices by serial number?

### ISSUE THREAD

**Issue by LeaseOnLife** [sbender9/signalk-venus-plugin#63]
I am running a PI3B with Venus OS and currently have 4 USB-VE-direct cables plugged in (2x BMV, 2x solar). When fiddling with that, and possibly adding more of these via USB hubs, the "VRM" numbers get reordered in VenusOS, which then screws up the logging into influxdb. 
My workaround is to re-map the inputs within the plugin, and that seems to work.
But I am wondering if the mapping could be made more consistent by reading the device's serial number. Preferably the controller's serial number, not the one from the USB dongle.
Thanks!
Dirk

**Comment by mpvader** [comment]
Hi Dirk,

I think a fix is coming: last week we implemented exactly this in the vedirect-serial driver in Venus OS - where it should be; as then also the numbering on the VRM Portal and so forth remains stable.

What remains stable after that change is the value under /DeviceInstance on D-Bus. It used to be tied to the usb-port number, and now its tied to the serial number of the charge controller (or BMV).

I'm pretty sure that will also fix it when taking the data through the signalk-venus-plugin, but you'll have to test to make sure.

Keep an eye out for a v2.70 beta, or updated [Venus OS large image](https://www.victronenergy.com/live/venus-os:large), in the coming weeks.

**Comment by LeaseOnLife** [comment]
Excellent! agreed, that is where it belongs.
I keep this open until then, also for others who stumble upon this..

**Comment by LeaseOnLife** [comment]
VenusOS 2.63~1 addresses this. VRM numbers on my system staid the same.
